import { BiLogoPostgresql } from "react-icons/bi";
import { BsFillBootstrapFill, BsRobot } from "react-icons/bs";
import { TbBeach, TbBrandFramerMotion } from "react-icons/tb";
import { FaNpm, FaGolang, FaCss3Alt, FaGitAlt } from "react-icons/fa6";
import { DiPhotoshop } from "react-icons/di";
import {
  SiExpress,
  SiFramer,
  SiGithub,
  SiHtml5,
  SiJavascript,
  SiNextdotjs,
  SiNodedotjs,
  SiPrisma,
  SiReact,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiLaravel,
  SiPhp,
  SiRedux,
  SiVuedotjs,
  SiFirebase,
  SiReactrouter,
  SiReacthookform,
  SiReacttable,
  SiMysql,
  SiMongodb,
  SiAstro,
  SiBun,
  SiYarn,
  SiNestjs,
  SiSupabase,
  SiJest,
  SiDocker,
  SiKotlin,
  SiJetpackcompose,
  SiZod,
  SiShadcnui,
  SiAxios,
  SiFigma,
  SiCoreldraw,
} from "react-icons/si";
import { RiShieldKeyholeFill } from "react-icons/ri";

export type SkillProps = {
  [key: string]: {
    icon: JSX.Element;
    background: string;
    color: string;
    isActive?: boolean;
    category: "Utama" | "Frontend" | "Backend" | "Database" | "Tools";
  };
};

const iconSize = 26;

export const STACKS: SkillProps = {
  HTML: {
    icon: <SiHtml5 size={iconSize} />,
    background: "#f97316",
    color: "text-orange-500",
    isActive: true,
    category: "Frontend",
  },
  CSS: {
    icon: <FaCss3Alt size={iconSize} />,
    background: "#3b82f6",
    color: "text-blue-500",
    isActive: true,
    category: "Frontend",
  },
  JavaScript: {
    icon: <SiJavascript size={iconSize} />,
    background: "#facc15",
    color: "text-yellow-400",
    isActive: true,
    category: "Frontend",
  },
  TypeScript: {
    icon: <SiTypescript size={iconSize} />,
    background: "#3178c6",
    color: "text-blue-500",
    isActive: true,
    category: "Frontend",
  },
  Bootstrap: {
    icon: <BsFillBootstrapFill size={iconSize} />,
    background: "#7c3aed",
    color: "text-violet-600",
    isActive: true,
    category: "Frontend",
  },
  TailwindCSS: {
    icon: <SiTailwindcss size={iconSize} />,
    background: "#38bdf8",
    color: "text-sky-400",
    isActive: true,
    category: "Utama",
  },
  Vite: {
    icon: <SiVite size={iconSize} />,
    background: "#a855f7",
    color: "text-purple-500",
    isActive: true,
    category: "Frontend",
  },
  "React.js": {
    icon: <SiReact size={iconSize} />,
    background: "#22d3ee",
    color: "text-cyan-400",
    isActive: true,
    category: "Utama",
  },
  "Next.js": {
    icon: <SiNextdotjs size={iconSize} />,
    background: "#404040",
    color: "text-neutral-50",
    isActive: true,
    category: "Utama",
  },
  "Node.js": {
    icon: <SiNodedotjs size={iconSize} />,
    background: "#16a34a",
    color: "text-green-600",
    isActive: true,
    category: "Utama",
  },
  "Express.js": {
    icon: <SiExpress size={iconSize} />,
    background: "#525252",
    color: "text-neutral-200",
    isActive: true,
    category: "Backend",
  },
  PHP: {
    icon: <SiPhp size={iconSize} />,
    background: "#818cf8",
    color: "text-indigo-400",
    isActive: true,
    category: "Backend",
  },
  Laravel: {
    icon: <SiLaravel size={iconSize} />,
    background: "#b91c1c",
    color: "text-red-600",
    isActive: true,
    category: "Utama",
  },
  MySQL: {
    icon: <SiMysql size={iconSize} />,
    background: "#0e7490",
    color: "text-cyan-700",
    isActive: true,
    category: "Database",
  },
  PostgreSQL: {
    icon: <BiLogoPostgresql size={iconSize} />,
    background: "#336791",
    color: "text-blue-400",
    isActive: true,
    category: "Database",
  },
  MongoDB: {
    icon: <SiMongodb size={iconSize} />,
    background: "#16a34a",
    color: "text-green-500",
    isActive: true,
    category: "Database",
  },
  Git: {
    icon: <FaGitAlt size={iconSize} />,
    background: "#ea580c",
    color: "text-orange-500",
    isActive: true,
    category: "Tools",
  },
  Github: {
    icon: <SiGithub size={iconSize} />,
    background: "#24292e",
    color: "text-neutral-100",
    isActive: true,
    category: "Tools",
  },
  Npm: {
    icon: <FaNpm size={iconSize} />,
    background: "#cc3534",
    color: "text-red-400",
    isActive: true,
    category: "Tools",
  },
  Yarn: {
    icon: <SiYarn size={iconSize} />,
    background: "#2c8ebb",
    color: "text-sky-400",
    isActive: true,
    category: "Tools",
  },
  Figma: {
    icon: <SiFigma size={iconSize} />,
    background: "#ec4899",
    color: "text-pink-500",
    isActive: true,
    category: "Tools",
  },
  Photoshop: {
    icon: <DiPhotoshop size={iconSize} />,
    background: "#001e36",
    color: "text-blue-300",
    isActive: true,
    category: "Tools",
  },
  CorelDraw: {
    icon: <SiCoreldraw size={iconSize} />,
    background: "#007940",
    color: "text-green-400",
    isActive: true,
    category: "Tools",
  },
  // Desactivated Skills
  "Vue.js": {
    icon: <SiVuedotjs size={iconSize} />,
    background: "bg-green-400",
    color: "text-green-400",
    isActive: false,
    category: "Frontend",
  },
  "Astro.js": {
    icon: <SiAstro size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: false,
    category: "Frontend",
  },
  "Shadcn UI": {
    icon: <SiShadcnui size={iconSize} />,
    background: "bg-neutral-800",
    color: "text-neutral-800",
    isActive: false,
    category: "Frontend",
  },
  "NextAuth.js": {
    icon: <RiShieldKeyholeFill size={iconSize} />,
    background: "bg-slate-800",
    color: "text-slate-800",
    isActive: false,
    category: "Backend",
  },
  TanStack: {
    icon: <TbBeach size={iconSize} />,
    background: "bg-amber-500",
    color: "text-amber-500",
    isActive: false,
    category: "Frontend",
  },
  "React Table": {
    icon: <SiReacttable size={iconSize} />,
    background: "bg-rose-600",
    color: "text-rose-600",
    isActive: false,
    category: "Frontend",
  },
  "React Hook Form": {
    icon: <SiReacthookform size={iconSize} />,
    background: "bg-pink-500",
    color: "text-pink-500",
    isActive: false,
    category: "Frontend",
  },
  "React Router": {
    icon: <SiReactrouter size={iconSize} />,
    background: "bg-red-500",
    color: "text-red-500",
    isActive: false,
    category: "Frontend",
  },
  Axios: {
    icon: <SiAxios size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: false,
    category: "Backend",
  },
  Zod: {
    icon: <SiZod size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-600",
    isActive: false,
    category: "Backend",
  },
  "Framer Motion": {
    icon: <TbBrandFramerMotion size={iconSize} />,
    background: "bg-yellow-400",
    color: "text-yellow-400",
    isActive: false,
    category: "Frontend",
  },
  Redux: {
    icon: <SiRedux size={iconSize} />,
    background: "bg-violet-500",
    color: "text-violet-500",
    isActive: false,
    category: "Frontend",
  },
  Prisma: {
    icon: <SiPrisma size={iconSize} />,
    background: "bg-teal-500",
    color: "text-teal-500",
    isActive: false,
    category: "Backend",
  },
  "Nest.js": {
    icon: <SiNestjs size={iconSize} />,
    background: "bg-rose-600",
    color: "text-rose-600",
    isActive: false,
    category: "Backend",
  },
  Go: {
    icon: <FaGolang size={iconSize} />,
    background: "bg-sky-500",
    color: "text-sky-500",
    isActive: false,
    category: "Backend",
  },
  Kotlin: {
    icon: <SiKotlin size={iconSize} />,
    background: "bg-violet-600",
    color: "text-violet-600",
    isActive: false,
    category: "Tools",
  },
  "Jetpack Compose": {
    icon: <SiJetpackcompose size={iconSize} />,
    background: "bg-cyan-800",
    color: "text-cyan-800",
    isActive: false,
    category: "Tools",
  },
  Firebase: {
    icon: <SiFirebase size={iconSize} />,
    background: "bg-amber-500",
    color: "text-amber-500",
    isActive: false,
    category: "Database",
  },
  Supabase: {
    icon: <SiSupabase size={iconSize} />,
    background: "bg-emerald-500",
    color: "text-emerald-500",
    isActive: false,
    category: "Database",
  },
  Jest: {
    icon: <SiJest size={iconSize} />,
    background: "bg-pink-600",
    color: "text-pink-600",
    isActive: false,
    category: "Tools",
  },
  Docker: {
    icon: <SiDocker size={iconSize} />,
    background: "bg-blue-600",
    color: "text-blue-500",
    isActive: false,
    category: "Tools",
  },
  AI: {
    icon: <BsRobot size={iconSize} />,
    background: "bg-fuchsia-700",
    color: "text-fuchsia-700",
    isActive: false,
    category: "Tools",
  },
  bun: {
    icon: <SiBun size={iconSize} />,
    background: "bg-orange-100",
    color: "text-yellow-50",
    isActive: false,
    category: "Tools",
  },
};
