# ─── Stage 1: Install dependencies ───────────────────────────────────────────
FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# ─── Stage 2: Build application ───────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public env vars diperlukan saat build (di-embed ke dalam JS bundle)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_AUTHOR_EMAIL
ARG NEXT_PUBLIC_AUTHOR_NAME
ARG NEXT_PUBLIC_AVATAR_URL
ARG NEXT_PUBLIC_GITHUB_USERNAME
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM
ARG NEXT_PUBLIC_SOCIAL_LINKEDIN
ARG NEXT_PUBLIC_SOCIAL_WHATSAPP
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_RESUME_URL
ARG NEXT_PUBLIC_WAKATIME_USERNAME
ARG NEXT_PUBLIC_UMAMI_USERNAME
ARG NEXT_PUBLIC_UMAMI_DOMAIN
ARG NEXT_PUBLIC_UMAMI_SHARE_URL
ARG NEXT_PUBLIC_MONKEYTYPE_USERNAME
ARG NEXT_PUBLIC_CODEWARS_USERNAME
ARG DOMAIN

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_AUTHOR_EMAIL=$NEXT_PUBLIC_AUTHOR_EMAIL
ENV NEXT_PUBLIC_AUTHOR_NAME=$NEXT_PUBLIC_AUTHOR_NAME
ENV NEXT_PUBLIC_AVATAR_URL=$NEXT_PUBLIC_AVATAR_URL
ENV NEXT_PUBLIC_GITHUB_USERNAME=$NEXT_PUBLIC_GITHUB_USERNAME
ENV NEXT_PUBLIC_SOCIAL_INSTAGRAM=$NEXT_PUBLIC_SOCIAL_INSTAGRAM
ENV NEXT_PUBLIC_SOCIAL_LINKEDIN=$NEXT_PUBLIC_SOCIAL_LINKEDIN
ENV NEXT_PUBLIC_SOCIAL_WHATSAPP=$NEXT_PUBLIC_SOCIAL_WHATSAPP
ENV NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER
ENV NEXT_PUBLIC_RESUME_URL=$NEXT_PUBLIC_RESUME_URL
ENV NEXT_PUBLIC_WAKATIME_USERNAME=$NEXT_PUBLIC_WAKATIME_USERNAME
ENV NEXT_PUBLIC_UMAMI_USERNAME=$NEXT_PUBLIC_UMAMI_USERNAME
ENV NEXT_PUBLIC_UMAMI_DOMAIN=$NEXT_PUBLIC_UMAMI_DOMAIN
ENV NEXT_PUBLIC_UMAMI_SHARE_URL=$NEXT_PUBLIC_UMAMI_SHARE_URL
ENV NEXT_PUBLIC_MONKEYTYPE_USERNAME=$NEXT_PUBLIC_MONKEYTYPE_USERNAME
ENV NEXT_PUBLIC_CODEWARS_USERNAME=$NEXT_PUBLIC_CODEWARS_USERNAME
ENV DOMAIN=$DOMAIN

RUN npm run build

# ─── Stage 3: Production runner ───────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Buat user non-root untuk keamanan
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Salin hasil build standalone
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# Runtime env vars (secret) — diisi via docker run -e atau docker-compose.yml
# Tidak di-hardcode di sini demi keamanan
# Contoh: NEXTAUTH_SECRET, GOOGLE_CLIENT_ID, dll. — lihat .env.example

CMD ["node", "server.js"]
